// Generated by go-wayland-scanner
// https://github.com/rajveermalviya/go-wayland/cmd/go-wayland-scanner
// XML file : third_party/protocols/ext-image-copy-capture-v1.xml
//
// ext_image_copy_capture_v1 Protocol Copyright:
//
// Copyright © 2021-2023 Andri Yngvason
// Copyright © 2024 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package extcapture

import "github.com/rajveermalviya/go-wayland/wayland/client"

// ExtImageCopyCaptureManagerV1 : manager to inform clients and begin capturing
//
// This object is a manager which offers requests to start capturing from a
// source.
type ExtImageCopyCaptureManagerV1 struct {
	client.BaseProxy
}

// NewExtImageCopyCaptureManagerV1 : manager to inform clients and begin capturing
//
// This object is a manager which offers requests to start capturing from a
// source.
func NewExtImageCopyCaptureManagerV1(ctx *client.Context) *ExtImageCopyCaptureManagerV1 {
	extImageCopyCaptureManagerV1 := &ExtImageCopyCaptureManagerV1{}
	ctx.Register(extImageCopyCaptureManagerV1)
	return extImageCopyCaptureManagerV1
}

// CreateSession : capture an image capture source
//
// Create a capturing session for an image capture source.
//
// If the paint_cursors option is set, cursors shall be composited onto
// the captured frame. The cursor must not be composited onto the frame
// if this flag is not set.
//
// If the options bitfield is invalid, the invalid_option protocol error
// is sent.
func (i *ExtImageCopyCaptureManagerV1) CreateSession(source *ExtImageCaptureSourceV1, options uint32) (*ExtImageCopyCaptureSessionV1, error) {
	session := NewExtImageCopyCaptureSessionV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], session.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], source.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(options))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return session, err
}

// CreatePointerCursorSession : capture the pointer cursor of an image capture source
//
// Create a cursor capturing session for the pointer of an image capture
// source.
func (i *ExtImageCopyCaptureManagerV1) CreatePointerCursorSession(source *ExtImageCaptureSourceV1, pointer *client.Pointer) (*ExtImageCopyCaptureCursorSessionV1, error) {
	session := NewExtImageCopyCaptureCursorSessionV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], session.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], source.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], pointer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return session, err
}

// Destroy : destroy the manager
//
// Destroy the manager object.
//
// Other objects created via this interface are unaffected.
func (i *ExtImageCopyCaptureManagerV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 2
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ExtImageCopyCaptureManagerV1Error uint32

// ExtImageCopyCaptureManagerV1Error :
const (
	// ExtImageCopyCaptureManagerV1ErrorInvalidOption : invalid option flag
	ExtImageCopyCaptureManagerV1ErrorInvalidOption ExtImageCopyCaptureManagerV1Error = 1
)

func (e ExtImageCopyCaptureManagerV1Error) Name() string {
	switch e {
	case ExtImageCopyCaptureManagerV1ErrorInvalidOption:
		return "invalid_option"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureManagerV1Error) Value() string {
	switch e {
	case ExtImageCopyCaptureManagerV1ErrorInvalidOption:
		return "1"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureManagerV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

type ExtImageCopyCaptureManagerV1Options uint32

// ExtImageCopyCaptureManagerV1Options :
const (
	// ExtImageCopyCaptureManagerV1OptionsPaintCursors : paint cursors onto captured frames
	ExtImageCopyCaptureManagerV1OptionsPaintCursors ExtImageCopyCaptureManagerV1Options = 1
)

func (e ExtImageCopyCaptureManagerV1Options) Name() string {
	switch e {
	case ExtImageCopyCaptureManagerV1OptionsPaintCursors:
		return "paint_cursors"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureManagerV1Options) Value() string {
	switch e {
	case ExtImageCopyCaptureManagerV1OptionsPaintCursors:
		return "1"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureManagerV1Options) String() string {
	return e.Name() + "=" + e.Value()
}

// ExtImageCopyCaptureSessionV1 : image copy capture session
//
// This object represents an active image copy capture session.
//
// After a capture session is created, buffer constraint events will be
// emitted from the compositor to tell the client which buffer types and
// formats are supported for reading from the session. The compositor may
// re-send buffer constraint events whenever they change.
//
// To advertise buffer constraints, the compositor must send in no
// particular order: zero or more shm_format and dmabuf_format events, zero
// or one dmabuf_device event, and exactly one buffer_size event. Then the
// compositor must send a done event.
//
// When the client has received all the buffer constraints, it can create a
// buffer accordingly, attach it to the capture session using the
// attach_buffer request, set the buffer damage using the damage_buffer
// request and then send the capture request.
type ExtImageCopyCaptureSessionV1 struct {
	client.BaseProxy
	bufferSizeHandler   ExtImageCopyCaptureSessionV1BufferSizeHandlerFunc
	shmFormatHandler    ExtImageCopyCaptureSessionV1ShmFormatHandlerFunc
	dmabufDeviceHandler ExtImageCopyCaptureSessionV1DmabufDeviceHandlerFunc
	dmabufFormatHandler ExtImageCopyCaptureSessionV1DmabufFormatHandlerFunc
	doneHandler         ExtImageCopyCaptureSessionV1DoneHandlerFunc
	stoppedHandler      ExtImageCopyCaptureSessionV1StoppedHandlerFunc
}

// NewExtImageCopyCaptureSessionV1 : image copy capture session
//
// This object represents an active image copy capture session.
//
// After a capture session is created, buffer constraint events will be
// emitted from the compositor to tell the client which buffer types and
// formats are supported for reading from the session. The compositor may
// re-send buffer constraint events whenever they change.
//
// To advertise buffer constraints, the compositor must send in no
// particular order: zero or more shm_format and dmabuf_format events, zero
// or one dmabuf_device event, and exactly one buffer_size event. Then the
// compositor must send a done event.
//
// When the client has received all the buffer constraints, it can create a
// buffer accordingly, attach it to the capture session using the
// attach_buffer request, set the buffer damage using the damage_buffer
// request and then send the capture request.
func NewExtImageCopyCaptureSessionV1(ctx *client.Context) *ExtImageCopyCaptureSessionV1 {
	extImageCopyCaptureSessionV1 := &ExtImageCopyCaptureSessionV1{}
	ctx.Register(extImageCopyCaptureSessionV1)
	return extImageCopyCaptureSessionV1
}

// CreateFrame : create a frame
//
// Create a capture frame for this session.
//
// At most one frame object can exist for a given session at any time. If
// a client sends a create_frame request before a previous frame object
// has been destroyed, the duplicate_frame protocol error is raised.
func (i *ExtImageCopyCaptureSessionV1) CreateFrame() (*ExtImageCopyCaptureFrameV1, error) {
	frame := NewExtImageCopyCaptureFrameV1(i.Context())
	const opcode = 0
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], frame.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return frame, err
}

// Destroy : delete this object
//
// Destroys the session. This request can be sent at any time by the
// client.
//
// This request doesn't affect ext_image_copy_capture_frame_v1 objects created by
// this object.
func (i *ExtImageCopyCaptureSessionV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 1
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ExtImageCopyCaptureSessionV1Error uint32

// ExtImageCopyCaptureSessionV1Error :
const (
	// ExtImageCopyCaptureSessionV1ErrorDuplicateFrame : create_frame sent before destroying previous frame
	ExtImageCopyCaptureSessionV1ErrorDuplicateFrame ExtImageCopyCaptureSessionV1Error = 1
)

func (e ExtImageCopyCaptureSessionV1Error) Name() string {
	switch e {
	case ExtImageCopyCaptureSessionV1ErrorDuplicateFrame:
		return "duplicate_frame"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureSessionV1Error) Value() string {
	switch e {
	case ExtImageCopyCaptureSessionV1ErrorDuplicateFrame:
		return "1"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureSessionV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

// ExtImageCopyCaptureSessionV1BufferSizeEvent : image capture source dimensions
//
// Provides the dimensions of the source image in buffer pixel coordinates.
//
// The client must attach buffers that match this size.
type ExtImageCopyCaptureSessionV1BufferSizeEvent struct {
	Width  uint32
	Height uint32
}
type ExtImageCopyCaptureSessionV1BufferSizeHandlerFunc func(ExtImageCopyCaptureSessionV1BufferSizeEvent)

// SetBufferSizeHandler : sets handler for ExtImageCopyCaptureSessionV1BufferSizeEvent
func (i *ExtImageCopyCaptureSessionV1) SetBufferSizeHandler(f ExtImageCopyCaptureSessionV1BufferSizeHandlerFunc) {
	i.bufferSizeHandler = f
}

// ExtImageCopyCaptureSessionV1ShmFormatEvent : shm buffer format
//
// Provides the format that must be used for shared-memory buffers.
//
// This event may be emitted multiple times, in which case the client may
// choose any given format.
type ExtImageCopyCaptureSessionV1ShmFormatEvent struct {
	Format uint32
}
type ExtImageCopyCaptureSessionV1ShmFormatHandlerFunc func(ExtImageCopyCaptureSessionV1ShmFormatEvent)

// SetShmFormatHandler : sets handler for ExtImageCopyCaptureSessionV1ShmFormatEvent
func (i *ExtImageCopyCaptureSessionV1) SetShmFormatHandler(f ExtImageCopyCaptureSessionV1ShmFormatHandlerFunc) {
	i.shmFormatHandler = f
}

// ExtImageCopyCaptureSessionV1DmabufDeviceEvent : dma-buf device
//
// This event advertises the device buffers must be allocated on for
// dma-buf buffers.
//
// In general the device is a DRM node. The DRM node type (primary vs.
// render) is unspecified. Clients must not rely on the compositor sending
// a particular node type. Clients cannot check two devices for equality
// by comparing the dev_t value.
type ExtImageCopyCaptureSessionV1DmabufDeviceEvent struct {
	Device []byte
}
type ExtImageCopyCaptureSessionV1DmabufDeviceHandlerFunc func(ExtImageCopyCaptureSessionV1DmabufDeviceEvent)

// SetDmabufDeviceHandler : sets handler for ExtImageCopyCaptureSessionV1DmabufDeviceEvent
func (i *ExtImageCopyCaptureSessionV1) SetDmabufDeviceHandler(f ExtImageCopyCaptureSessionV1DmabufDeviceHandlerFunc) {
	i.dmabufDeviceHandler = f
}

// ExtImageCopyCaptureSessionV1DmabufFormatEvent : dma-buf format
//
// Provides the format that must be used for dma-buf buffers.
//
// The client may choose any of the modifiers advertised in the array of
// 64-bit unsigned integers.
//
// This event may be emitted multiple times, in which case the client may
// choose any given format.
type ExtImageCopyCaptureSessionV1DmabufFormatEvent struct {
	Format    uint32
	Modifiers []byte
}
type ExtImageCopyCaptureSessionV1DmabufFormatHandlerFunc func(ExtImageCopyCaptureSessionV1DmabufFormatEvent)

// SetDmabufFormatHandler : sets handler for ExtImageCopyCaptureSessionV1DmabufFormatEvent
func (i *ExtImageCopyCaptureSessionV1) SetDmabufFormatHandler(f ExtImageCopyCaptureSessionV1DmabufFormatHandlerFunc) {
	i.dmabufFormatHandler = f
}

// ExtImageCopyCaptureSessionV1DoneEvent : all constraints have been sent
//
// This event is sent once when all buffer constraint events have been
// sent.
//
// The compositor must always end a batch of buffer constraint events with
// this event, regardless of whether it sends the initial constraints or
// an update.
type ExtImageCopyCaptureSessionV1DoneEvent struct{}
type ExtImageCopyCaptureSessionV1DoneHandlerFunc func(ExtImageCopyCaptureSessionV1DoneEvent)

// SetDoneHandler : sets handler for ExtImageCopyCaptureSessionV1DoneEvent
func (i *ExtImageCopyCaptureSessionV1) SetDoneHandler(f ExtImageCopyCaptureSessionV1DoneHandlerFunc) {
	i.doneHandler = f
}

// ExtImageCopyCaptureSessionV1StoppedEvent : session is no longer available
//
// This event indicates that the capture session has stopped and is no
// longer available. This can happen in a number of cases, e.g. when the
// underlying source is destroyed, if the user decides to end the image
// capture, or if an unrecoverable runtime error has occurred.
//
// The client should destroy the session after receiving this event.
type ExtImageCopyCaptureSessionV1StoppedEvent struct{}
type ExtImageCopyCaptureSessionV1StoppedHandlerFunc func(ExtImageCopyCaptureSessionV1StoppedEvent)

// SetStoppedHandler : sets handler for ExtImageCopyCaptureSessionV1StoppedEvent
func (i *ExtImageCopyCaptureSessionV1) SetStoppedHandler(f ExtImageCopyCaptureSessionV1StoppedHandlerFunc) {
	i.stoppedHandler = f
}

func (i *ExtImageCopyCaptureSessionV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.bufferSizeHandler == nil {
			return
		}
		var e ExtImageCopyCaptureSessionV1BufferSizeEvent
		l := 0
		e.Width = client.Uint32(data[l : l+4])
		l += 4
		e.Height = client.Uint32(data[l : l+4])
		l += 4

		i.bufferSizeHandler(e)
	case 1:
		if i.shmFormatHandler == nil {
			return
		}
		var e ExtImageCopyCaptureSessionV1ShmFormatEvent
		l := 0
		e.Format = client.Uint32(data[l : l+4])
		l += 4

		i.shmFormatHandler(e)
	case 2:
		if i.dmabufDeviceHandler == nil {
			return
		}
		var e ExtImageCopyCaptureSessionV1DmabufDeviceEvent
		l := 0
		deviceLen := int(client.Uint32(data[l : l+4]))
		l += 4
		e.Device = make([]byte, deviceLen)
		copy(e.Device, data[l:l+deviceLen])
		l += deviceLen

		i.dmabufDeviceHandler(e)
	case 3:
		if i.dmabufFormatHandler == nil {
			return
		}
		var e ExtImageCopyCaptureSessionV1DmabufFormatEvent
		l := 0
		e.Format = client.Uint32(data[l : l+4])
		l += 4
		modifiersLen := int(client.Uint32(data[l : l+4]))
		l += 4
		e.Modifiers = make([]byte, modifiersLen)
		copy(e.Modifiers, data[l:l+modifiersLen])
		l += modifiersLen

		i.dmabufFormatHandler(e)
	case 4:
		if i.doneHandler == nil {
			return
		}
		var e ExtImageCopyCaptureSessionV1DoneEvent

		i.doneHandler(e)
	case 5:
		if i.stoppedHandler == nil {
			return
		}
		var e ExtImageCopyCaptureSessionV1StoppedEvent

		i.stoppedHandler(e)
	}
}

// ExtImageCopyCaptureFrameV1 : image capture frame
//
// This object represents an image capture frame.
//
// The client should attach a buffer, damage the buffer, and then send a
// capture request.
//
// If the capture is successful, the compositor must send the frame metadata
// (transform, damage, presentation_time in any order) followed by the ready
// event.
//
// If the capture fails, the compositor must send the failed event.
type ExtImageCopyCaptureFrameV1 struct {
	client.BaseProxy
	transformHandler        ExtImageCopyCaptureFrameV1TransformHandlerFunc
	damageHandler           ExtImageCopyCaptureFrameV1DamageHandlerFunc
	presentationTimeHandler ExtImageCopyCaptureFrameV1PresentationTimeHandlerFunc
	readyHandler            ExtImageCopyCaptureFrameV1ReadyHandlerFunc
	failedHandler           ExtImageCopyCaptureFrameV1FailedHandlerFunc
}

// NewExtImageCopyCaptureFrameV1 : image capture frame
//
// This object represents an image capture frame.
//
// The client should attach a buffer, damage the buffer, and then send a
// capture request.
//
// If the capture is successful, the compositor must send the frame metadata
// (transform, damage, presentation_time in any order) followed by the ready
// event.
//
// If the capture fails, the compositor must send the failed event.
func NewExtImageCopyCaptureFrameV1(ctx *client.Context) *ExtImageCopyCaptureFrameV1 {
	extImageCopyCaptureFrameV1 := &ExtImageCopyCaptureFrameV1{}
	ctx.Register(extImageCopyCaptureFrameV1)
	return extImageCopyCaptureFrameV1
}

// Destroy : destroy this object
//
// Destroys the frame. This request can be sent at any time by the
// client.
func (i *ExtImageCopyCaptureFrameV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// AttachBuffer : attach buffer to session
//
// Attach a buffer to the session.
//
// The wl_buffer.release request is unused.
//
// The new buffer replaces any previously attached buffer.
//
// This request must not be sent after capture, or else the
// already_captured protocol error is raised.
func (i *ExtImageCopyCaptureFrameV1) AttachBuffer(buffer *client.Buffer) error {
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], buffer.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// DamageBuffer : damage buffer
//
// Apply damage to the buffer which is to be captured next. This request
// may be sent multiple times to describe a region.
//
// The client indicates the accumulated damage since this wl_buffer was
// last captured. During capture, the compositor will update the buffer
// with at least the union of the region passed by the client and the
// region advertised by ext_image_copy_capture_frame_v1.damage.
//
// When a wl_buffer is captured for the first time, or when the client
// doesn't track damage, the client must damage the whole buffer.
//
// This is for optimisation purposes. The compositor may use this
// information to reduce copying.
//
// These coordinates originate from the upper left corner of the buffer.
//
// If x or y are strictly negative, or if width or height are negative or
// zero, the invalid_buffer_damage protocol error is raised.
//
// This request must not be sent after capture, or else the
// already_captured protocol error is raised.
//
//	x: region x coordinate
//	y: region y coordinate
//	width: region width
//	height: region height
func (i *ExtImageCopyCaptureFrameV1) DamageBuffer(x, y, width, height int32) error {
	const opcode = 2
	const _reqBufLen = 8 + 4 + 4 + 4 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(x))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(y))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(width))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(height))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// Capture : capture a frame
//
// Capture a frame.
//
// Unless this is the first successful captured frame performed in this
// session, the compositor may wait an indefinite amount of time for the
// source content to change before performing the copy.
//
// This request may only be sent once, or else the already_captured
// protocol error is raised. A buffer must be attached before this request
// is sent, or else the no_buffer protocol error is raised.
func (i *ExtImageCopyCaptureFrameV1) Capture() error {
	const opcode = 3
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

type ExtImageCopyCaptureFrameV1Error uint32

// ExtImageCopyCaptureFrameV1Error :
const (
	// ExtImageCopyCaptureFrameV1ErrorNoBuffer : capture sent without attach_buffer
	ExtImageCopyCaptureFrameV1ErrorNoBuffer ExtImageCopyCaptureFrameV1Error = 1
	// ExtImageCopyCaptureFrameV1ErrorInvalidBufferDamage : invalid buffer damage
	ExtImageCopyCaptureFrameV1ErrorInvalidBufferDamage ExtImageCopyCaptureFrameV1Error = 2
	// ExtImageCopyCaptureFrameV1ErrorAlreadyCaptured : capture request has been sent
	ExtImageCopyCaptureFrameV1ErrorAlreadyCaptured ExtImageCopyCaptureFrameV1Error = 3
)

func (e ExtImageCopyCaptureFrameV1Error) Name() string {
	switch e {
	case ExtImageCopyCaptureFrameV1ErrorNoBuffer:
		return "no_buffer"
	case ExtImageCopyCaptureFrameV1ErrorInvalidBufferDamage:
		return "invalid_buffer_damage"
	case ExtImageCopyCaptureFrameV1ErrorAlreadyCaptured:
		return "already_captured"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureFrameV1Error) Value() string {
	switch e {
	case ExtImageCopyCaptureFrameV1ErrorNoBuffer:
		return "1"
	case ExtImageCopyCaptureFrameV1ErrorInvalidBufferDamage:
		return "2"
	case ExtImageCopyCaptureFrameV1ErrorAlreadyCaptured:
		return "3"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureFrameV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

type ExtImageCopyCaptureFrameV1FailureReason uint32

// ExtImageCopyCaptureFrameV1FailureReason :
const (
	ExtImageCopyCaptureFrameV1FailureReasonUnknown           ExtImageCopyCaptureFrameV1FailureReason = 0
	ExtImageCopyCaptureFrameV1FailureReasonBufferConstraints ExtImageCopyCaptureFrameV1FailureReason = 1
	ExtImageCopyCaptureFrameV1FailureReasonStopped           ExtImageCopyCaptureFrameV1FailureReason = 2
)

func (e ExtImageCopyCaptureFrameV1FailureReason) Name() string {
	switch e {
	case ExtImageCopyCaptureFrameV1FailureReasonUnknown:
		return "unknown"
	case ExtImageCopyCaptureFrameV1FailureReasonBufferConstraints:
		return "buffer_constraints"
	case ExtImageCopyCaptureFrameV1FailureReasonStopped:
		return "stopped"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureFrameV1FailureReason) Value() string {
	switch e {
	case ExtImageCopyCaptureFrameV1FailureReasonUnknown:
		return "0"
	case ExtImageCopyCaptureFrameV1FailureReasonBufferConstraints:
		return "1"
	case ExtImageCopyCaptureFrameV1FailureReasonStopped:
		return "2"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureFrameV1FailureReason) String() string {
	return e.Name() + "=" + e.Value()
}

// ExtImageCopyCaptureFrameV1TransformEvent : buffer transform
//
// This event is sent before the ready event and holds the transform that
// the compositor has applied to the buffer contents.
type ExtImageCopyCaptureFrameV1TransformEvent struct {
	Transform uint32
}
type ExtImageCopyCaptureFrameV1TransformHandlerFunc func(ExtImageCopyCaptureFrameV1TransformEvent)

// SetTransformHandler : sets handler for ExtImageCopyCaptureFrameV1TransformEvent
func (i *ExtImageCopyCaptureFrameV1) SetTransformHandler(f ExtImageCopyCaptureFrameV1TransformHandlerFunc) {
	i.transformHandler = f
}

// ExtImageCopyCaptureFrameV1DamageEvent : buffer damaged region
//
// This event is sent before the ready event. It may be generated multiple
// times to describe a region.
//
// The first captured frame in a session will always carry full damage.
// Subsequent frames' damaged regions describe which parts of the buffer
// have changed since the last ready event.
//
// These coordinates originate in the upper left corner of the buffer.
type ExtImageCopyCaptureFrameV1DamageEvent struct {
	X      int32
	Y      int32
	Width  int32
	Height int32
}
type ExtImageCopyCaptureFrameV1DamageHandlerFunc func(ExtImageCopyCaptureFrameV1DamageEvent)

// SetDamageHandler : sets handler for ExtImageCopyCaptureFrameV1DamageEvent
func (i *ExtImageCopyCaptureFrameV1) SetDamageHandler(f ExtImageCopyCaptureFrameV1DamageHandlerFunc) {
	i.damageHandler = f
}

// ExtImageCopyCaptureFrameV1PresentationTimeEvent : presentation time of the frame
//
// This event indicates the time at which the frame is presented to the
// output in system monotonic time. This event is sent before the ready
// event.
//
// The timestamp is expressed as tv_sec_hi, tv_sec_lo, tv_nsec triples,
// each component being an unsigned 32-bit value. Whole seconds are in
// tv_sec which is a 64-bit value combined from tv_sec_hi and tv_sec_lo,
// and the additional fractional part in tv_nsec as nanoseconds. Hence,
// for valid timestamps tv_nsec must be in [0, 999999999].
type ExtImageCopyCaptureFrameV1PresentationTimeEvent struct {
	TvSecHi uint32
	TvSecLo uint32
	TvNsec  uint32
}
type ExtImageCopyCaptureFrameV1PresentationTimeHandlerFunc func(ExtImageCopyCaptureFrameV1PresentationTimeEvent)

// SetPresentationTimeHandler : sets handler for ExtImageCopyCaptureFrameV1PresentationTimeEvent
func (i *ExtImageCopyCaptureFrameV1) SetPresentationTimeHandler(f ExtImageCopyCaptureFrameV1PresentationTimeHandlerFunc) {
	i.presentationTimeHandler = f
}

// ExtImageCopyCaptureFrameV1ReadyEvent : frame is available for reading
//
// Called as soon as the frame is copied, indicating it is available
// for reading.
//
// The buffer may be re-used by the client after this event.
//
// After receiving this event, the client must destroy the object.
type ExtImageCopyCaptureFrameV1ReadyEvent struct{}
type ExtImageCopyCaptureFrameV1ReadyHandlerFunc func(ExtImageCopyCaptureFrameV1ReadyEvent)

// SetReadyHandler : sets handler for ExtImageCopyCaptureFrameV1ReadyEvent
func (i *ExtImageCopyCaptureFrameV1) SetReadyHandler(f ExtImageCopyCaptureFrameV1ReadyHandlerFunc) {
	i.readyHandler = f
}

// ExtImageCopyCaptureFrameV1FailedEvent : capture failed
//
// This event indicates that the attempted frame copy has failed.
//
// After receiving this event, the client must destroy the object.
type ExtImageCopyCaptureFrameV1FailedEvent struct {
	Reason uint32
}
type ExtImageCopyCaptureFrameV1FailedHandlerFunc func(ExtImageCopyCaptureFrameV1FailedEvent)

// SetFailedHandler : sets handler for ExtImageCopyCaptureFrameV1FailedEvent
func (i *ExtImageCopyCaptureFrameV1) SetFailedHandler(f ExtImageCopyCaptureFrameV1FailedHandlerFunc) {
	i.failedHandler = f
}

func (i *ExtImageCopyCaptureFrameV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.transformHandler == nil {
			return
		}
		var e ExtImageCopyCaptureFrameV1TransformEvent
		l := 0
		e.Transform = client.Uint32(data[l : l+4])
		l += 4

		i.transformHandler(e)
	case 1:
		if i.damageHandler == nil {
			return
		}
		var e ExtImageCopyCaptureFrameV1DamageEvent
		l := 0
		e.X = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Y = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Width = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Height = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.damageHandler(e)
	case 2:
		if i.presentationTimeHandler == nil {
			return
		}
		var e ExtImageCopyCaptureFrameV1PresentationTimeEvent
		l := 0
		e.TvSecHi = client.Uint32(data[l : l+4])
		l += 4
		e.TvSecLo = client.Uint32(data[l : l+4])
		l += 4
		e.TvNsec = client.Uint32(data[l : l+4])
		l += 4

		i.presentationTimeHandler(e)
	case 3:
		if i.readyHandler == nil {
			return
		}
		var e ExtImageCopyCaptureFrameV1ReadyEvent

		i.readyHandler(e)
	case 4:
		if i.failedHandler == nil {
			return
		}
		var e ExtImageCopyCaptureFrameV1FailedEvent
		l := 0
		e.Reason = client.Uint32(data[l : l+4])
		l += 4

		i.failedHandler(e)
	}
}

// ExtImageCopyCaptureCursorSessionV1 : cursor capture session
//
// This object represents a cursor capture session. It extends the base
// capture session with cursor-specific metadata.
type ExtImageCopyCaptureCursorSessionV1 struct {
	client.BaseProxy
	enterHandler    ExtImageCopyCaptureCursorSessionV1EnterHandlerFunc
	leaveHandler    ExtImageCopyCaptureCursorSessionV1LeaveHandlerFunc
	positionHandler ExtImageCopyCaptureCursorSessionV1PositionHandlerFunc
	hotspotHandler  ExtImageCopyCaptureCursorSessionV1HotspotHandlerFunc
}

// NewExtImageCopyCaptureCursorSessionV1 : cursor capture session
//
// This object represents a cursor capture session. It extends the base
// capture session with cursor-specific metadata.
func NewExtImageCopyCaptureCursorSessionV1(ctx *client.Context) *ExtImageCopyCaptureCursorSessionV1 {
	extImageCopyCaptureCursorSessionV1 := &ExtImageCopyCaptureCursorSessionV1{}
	ctx.Register(extImageCopyCaptureCursorSessionV1)
	return extImageCopyCaptureCursorSessionV1
}

// Destroy : delete this object
//
// Destroys the session. This request can be sent at any time by the
// client.
//
// This request doesn't affect ext_image_copy_capture_frame_v1 objects created by
// this object.
func (i *ExtImageCopyCaptureCursorSessionV1) Destroy() error {
	defer i.Context().Unregister(i)
	const opcode = 0
	const _reqBufLen = 8
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return err
}

// GetCaptureSession : get image copy capturer session
//
// Gets the image copy capture session for this cursor session.
//
// The session will produce frames of the cursor image. The compositor may
// pause the session when the cursor leaves the captured area.
//
// This request must not be sent more than once, or else the
// duplicate_session protocol error is raised.
func (i *ExtImageCopyCaptureCursorSessionV1) GetCaptureSession() (*ExtImageCopyCaptureSessionV1, error) {
	session := NewExtImageCopyCaptureSessionV1(i.Context())
	const opcode = 1
	const _reqBufLen = 8 + 4
	var _reqBuf [_reqBufLen]byte
	l := 0
	client.PutUint32(_reqBuf[l:4], i.ID())
	l += 4
	client.PutUint32(_reqBuf[l:l+4], uint32(_reqBufLen<<16|opcode&0x0000ffff))
	l += 4
	client.PutUint32(_reqBuf[l:l+4], session.ID())
	l += 4
	err := i.Context().WriteMsg(_reqBuf[:], nil)
	return session, err
}

type ExtImageCopyCaptureCursorSessionV1Error uint32

// ExtImageCopyCaptureCursorSessionV1Error :
const (
	// ExtImageCopyCaptureCursorSessionV1ErrorDuplicateSession : get_capture_session sent twice
	ExtImageCopyCaptureCursorSessionV1ErrorDuplicateSession ExtImageCopyCaptureCursorSessionV1Error = 1
)

func (e ExtImageCopyCaptureCursorSessionV1Error) Name() string {
	switch e {
	case ExtImageCopyCaptureCursorSessionV1ErrorDuplicateSession:
		return "duplicate_session"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureCursorSessionV1Error) Value() string {
	switch e {
	case ExtImageCopyCaptureCursorSessionV1ErrorDuplicateSession:
		return "1"
	default:
		return ""
	}
}

func (e ExtImageCopyCaptureCursorSessionV1Error) String() string {
	return e.Name() + "=" + e.Value()
}

// ExtImageCopyCaptureCursorSessionV1EnterEvent : cursor entered captured area
//
// Sent when a cursor enters the captured area. It shall be generated
// before the "position" and "hotspot" events when and only when a cursor
// enters the area.
//
// The cursor enters the captured area when the cursor image intersects
// with the captured area. Note, this is different from e.g.
// wl_pointer.enter.
type ExtImageCopyCaptureCursorSessionV1EnterEvent struct{}
type ExtImageCopyCaptureCursorSessionV1EnterHandlerFunc func(ExtImageCopyCaptureCursorSessionV1EnterEvent)

// SetEnterHandler : sets handler for ExtImageCopyCaptureCursorSessionV1EnterEvent
func (i *ExtImageCopyCaptureCursorSessionV1) SetEnterHandler(f ExtImageCopyCaptureCursorSessionV1EnterHandlerFunc) {
	i.enterHandler = f
}

// ExtImageCopyCaptureCursorSessionV1LeaveEvent : cursor left captured area
//
// Sent when a cursor leaves the captured area. No "position" or "hotspot"
// event is generated for the cursor until the cursor enters the captured
// area again.
type ExtImageCopyCaptureCursorSessionV1LeaveEvent struct{}
type ExtImageCopyCaptureCursorSessionV1LeaveHandlerFunc func(ExtImageCopyCaptureCursorSessionV1LeaveEvent)

// SetLeaveHandler : sets handler for ExtImageCopyCaptureCursorSessionV1LeaveEvent
func (i *ExtImageCopyCaptureCursorSessionV1) SetLeaveHandler(f ExtImageCopyCaptureCursorSessionV1LeaveHandlerFunc) {
	i.leaveHandler = f
}

// ExtImageCopyCaptureCursorSessionV1PositionEvent : position changed
//
// Cursors outside the image capture source do not get captured and no
// event will be generated for them.
//
// The given position is the position of the cursor's hotspot and it is
// relative to the main buffer's top left corner in transformed buffer
// pixel coordinates. The coordinates may be negative or greater than the
// main buffer size.
type ExtImageCopyCaptureCursorSessionV1PositionEvent struct {
	X int32
	Y int32
}
type ExtImageCopyCaptureCursorSessionV1PositionHandlerFunc func(ExtImageCopyCaptureCursorSessionV1PositionEvent)

// SetPositionHandler : sets handler for ExtImageCopyCaptureCursorSessionV1PositionEvent
func (i *ExtImageCopyCaptureCursorSessionV1) SetPositionHandler(f ExtImageCopyCaptureCursorSessionV1PositionHandlerFunc) {
	i.positionHandler = f
}

// ExtImageCopyCaptureCursorSessionV1HotspotEvent : hotspot changed
//
// The hotspot describes the offset between the cursor image and the
// position of the input device.
//
// The given coordinates are the hotspot's offset from the origin in
// buffer coordinates.
//
// Clients should not apply the hotspot immediately: the hotspot becomes
// effective when the next ext_image_copy_capture_frame_v1.ready event is received.
//
// Compositors may delay this event until the client captures a new frame.
type ExtImageCopyCaptureCursorSessionV1HotspotEvent struct {
	X int32
	Y int32
}
type ExtImageCopyCaptureCursorSessionV1HotspotHandlerFunc func(ExtImageCopyCaptureCursorSessionV1HotspotEvent)

// SetHotspotHandler : sets handler for ExtImageCopyCaptureCursorSessionV1HotspotEvent
func (i *ExtImageCopyCaptureCursorSessionV1) SetHotspotHandler(f ExtImageCopyCaptureCursorSessionV1HotspotHandlerFunc) {
	i.hotspotHandler = f
}

func (i *ExtImageCopyCaptureCursorSessionV1) Dispatch(opcode uint32, fd int, data []byte) {
	switch opcode {
	case 0:
		if i.enterHandler == nil {
			return
		}
		var e ExtImageCopyCaptureCursorSessionV1EnterEvent

		i.enterHandler(e)
	case 1:
		if i.leaveHandler == nil {
			return
		}
		var e ExtImageCopyCaptureCursorSessionV1LeaveEvent

		i.leaveHandler(e)
	case 2:
		if i.positionHandler == nil {
			return
		}
		var e ExtImageCopyCaptureCursorSessionV1PositionEvent
		l := 0
		e.X = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Y = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.positionHandler(e)
	case 3:
		if i.hotspotHandler == nil {
			return
		}
		var e ExtImageCopyCaptureCursorSessionV1HotspotEvent
		l := 0
		e.X = int32(client.Uint32(data[l : l+4]))
		l += 4
		e.Y = int32(client.Uint32(data[l : l+4]))
		l += 4

		i.hotspotHandler(e)
	}
}
