// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Analytics {
    /**
     * Creates a new Analytics instance.
     * @param {Partial<Analytics>} [$$source = {}] - The source object to create the Analytics.
     */
    constructor($$source = {}) {
        if (!("invValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["invValue"] = 0;
        }
        if (!("ducats" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ducats"] = 0;
        }
        if (!("sellable" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sellable"] = 0;
        }
        if (!("tradeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tradeCount"] = 0;
        }
        if (!("netPlat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["netPlat"] = 0;
        }
        if (!("platIn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platIn"] = 0;
        }
        if (!("platOut" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platOut"] = 0;
        }
        if (!("cumulative" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["cumulative"] = [];
        }
        if (!("recent" in $$source)) {
            /**
             * @member
             * @type {TradeRow[]}
             */
            this["recent"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Analytics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Analytics}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cumulative" in $$parsedSource) {
            $$parsedSource["cumulative"] = $$createField7_0($$parsedSource["cumulative"]);
        }
        if ("recent" in $$parsedSource) {
            $$parsedSource["recent"] = $$createField8_0($$parsedSource["recent"]);
        }
        return new Analytics(/** @type {Partial<Analytics>} */($$parsedSource));
    }
}

/**
 * CraftNode is one node of an item's crafting tree: the target item at the root,
 * its recipe components as children, and (for buildable components) their own
 * recipes nested beneath. Need is the total quantity required at this position
 * (parent need × recipe count); Have is how many the player owns.
 */
export class CraftNode {
    /**
     * Creates a new CraftNode instance.
     * @param {Partial<CraftNode>} [$$source = {}] - The source object to create the CraftNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("need" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["need"] = 0;
        }
        if (!("have" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["have"] = 0;
        }
        if (!("enough" in $$source)) {
            /**
             * Have >= Need
             * @member
             * @type {boolean}
             */
            this["enough"] = false;
        }
        if (!("isResource" in $$source)) {
            /**
             * bulk resource vs. an acquirable part
             * @member
             * @type {boolean}
             */
            this["isResource"] = false;
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {CraftNode[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CraftNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CraftNode}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField6_0($$parsedSource["children"]);
        }
        return new CraftNode(/** @type {Partial<CraftNode>} */($$parsedSource));
    }
}

/**
 * FoundryItem is one build currently crafting in the foundry.
 */
export class FoundryItem {
    /**
     * Creates a new FoundryItem instance.
     * @param {Partial<FoundryItem>} [$$source = {}] - The source object to create the FoundryItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("completionMs" in $$source)) {
            /**
             * CompletionMs is the finish time in Unix milliseconds, so the frontend can
             * render a live countdown that stays accurate without re-scraping.
             * @member
             * @type {number}
             */
            this["completionMs"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * Done is true if the build already finished (completion is in the past).
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FoundryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FoundryItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FoundryItem(/** @type {Partial<FoundryItem>} */($$parsedSource));
    }
}

/**
 * InvCategory groups inventory items.
 */
export class InvCategory {
    /**
     * Creates a new InvCategory instance.
     * @param {Partial<InvCategory>} [$$source = {}] - The source object to create the InvCategory.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {InvItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvCategory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InvCategory}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new InvCategory(/** @type {Partial<InvCategory>} */($$parsedSource));
    }
}

/**
 * InvItem is a displayed inventory item.
 */
export class InvItem {
    /**
     * Creates a new InvItem instance.
     * @param {Partial<InvItem>} [$$source = {}] - The source object to create the InvItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rank"] = 0;
        }
        if (!("maxRank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRank"] = 0;
        }
        if (!("mastered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mastered"] = false;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InvItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InvItem(/** @type {Partial<InvItem>} */($$parsedSource));
    }
}

/**
 * ListResult reports the outcome of posting a sell order.
 */
export class ListResult {
    /**
     * Creates a new ListResult instance.
     * @param {Partial<ListResult>} [$$source = {}] - The source object to create the ListResult.
     */
    constructor($$source = {}) {
        if (!("listed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["listed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListResult(/** @type {Partial<ListResult>} */($$parsedSource));
    }
}

/**
 * LoadStatus reports whether the inventory is loaded and any error.
 */
export class LoadStatus {
    /**
     * Creates a new LoadStatus instance.
     * @param {Partial<LoadStatus>} [$$source = {}] - The source object to create the LoadStatus.
     */
    constructor($$source = {}) {
        if (!("loaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loaded"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadStatus(/** @type {Partial<LoadStatus>} */($$parsedSource));
    }
}

/**
 * MarketSeller is one warframe.market seller of a part, with a ready-to-send
 * in-game whisper to buy it.
 */
export class MarketSeller {
    /**
     * Creates a new MarketSeller instance.
     * @param {Partial<MarketSeller>} [$$source = {}] - The source object to create the MarketSeller.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("platinum" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platinum"] = 0;
        }
        if (!("quantity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quantity"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * ingame | online | offline
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("whisper" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["whisper"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketSeller instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketSeller}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarketSeller(/** @type {Partial<MarketSeller>} */($$parsedSource));
    }
}

export class MarketStatus {
    /**
     * Creates a new MarketStatus instance.
     * @param {Partial<MarketStatus>} [$$source = {}] - The source object to create the MarketStatus.
     */
    constructor($$source = {}) {
        if (!("loggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loggedIn"] = false;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("statusMode" in $$source)) {
            /**
             * auto | online | ingame | invisible
             * @member
             * @type {string}
             */
            this["statusMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarketStatus(/** @type {Partial<MarketStatus>} */($$parsedSource));
    }
}

export class MasteryItem {
    /**
     * Creates a new MasteryItem instance.
     * @param {Partial<MasteryItem>} [$$source = {}] - The source object to create the MasteryItem.
     */
    constructor($$source = {}) {
        if (!("uniqueName" in $$source)) {
            /**
             * UniqueName is the game's stable per-item id; the frontend keys its list on
             * it because display Name is NOT unique (e.g. two distinct "Grimoire" pistols).
             * @member
             * @type {string}
             */
            this["uniqueName"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "Mastered" etc (display string)
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("rank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rank"] = 0;
        }
        if (!("maxRank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRank"] = 0;
        }
        if (!("owned" in $$source)) {
            /**
             * a copy is currently in the inventory
             * @member
             * @type {boolean}
             */
            this["owned"] = false;
        }
        if (!("partsOwned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["partsOwned"] = 0;
        }
        if (!("partsTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["partsTotal"] = 0;
        }
        if (!("parts" in $$source)) {
            /**
             * per-component detail (collecting items)
             * @member
             * @type {MasteryPart[]}
             */
            this["parts"] = [];
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("buildCost" in $$source)) {
            /**
             * BuildCost is the platinum needed to buy the still-missing parts.
             * @member
             * @type {number}
             */
            this["buildCost"] = 0;
        }
        if (!("costKnown" in $$source)) {
            /**
             * CostKnown is false when a needed part has no market price (BuildCost partial).
             * @member
             * @type {boolean}
             */
            this["costKnown"] = false;
        }
        if (!("relicCount" in $$source)) {
            /**
             * RelicCount is how many owned relics can drop a still-needed part.
             * @member
             * @type {number}
             */
            this["relicCount"] = 0;
        }
        if (!("relicScore" in $$source)) {
            /**
             * RelicScore weights drop chance by owned-relic count (the "farmable" rank key).
             * @member
             * @type {number}
             */
            this["relicScore"] = 0;
        }
        if (!("bestChance" in $$source)) {
            /**
             * BestChance is the best single-relic drop chance (%) for a needed part.
             * @member
             * @type {number}
             */
            this["bestChance"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasteryItem}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parts" in $$parsedSource) {
            $$parsedSource["parts"] = $$createField9_0($$parsedSource["parts"]);
        }
        return new MasteryItem(/** @type {Partial<MasteryItem>} */($$parsedSource));
    }
}

/**
 * MasteryPart is one recipe component with how many the player owns vs needs
 * (recipes can require more than one, e.g. two blades).
 */
export class MasteryPart {
    /**
     * Creates a new MasteryPart instance.
     * @param {Partial<MasteryPart>} [$$source = {}] - The source object to create the MasteryPart.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * "<item> <component>" for market lookup
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("have" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["have"] = 0;
        }
        if (!("need" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["need"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteryPart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasteryPart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasteryPart(/** @type {Partial<MasteryPart>} */($$parsedSource));
    }
}

export class MasterySummary {
    /**
     * Creates a new MasterySummary instance.
     * @param {Partial<MasterySummary>} [$$source = {}] - The source object to create the MasterySummary.
     */
    constructor($$source = {}) {
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("Mastered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Mastered"] = 0;
        }
        if (!("BuiltUnranked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["BuiltUnranked"] = 0;
        }
        if (!("ReadyToBuild" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ReadyToBuild"] = 0;
        }
        if (!("PartsPartial" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PartsPartial"] = 0;
        }
        if (!("NotStarted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["NotStarted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterySummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterySummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterySummary(/** @type {Partial<MasterySummary>} */($$parsedSource));
    }
}

export class MasteryView {
    /**
     * Creates a new MasteryView instance.
     * @param {Partial<MasteryView>} [$$source = {}] - The source object to create the MasteryView.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {MasterySummary}
             */
            this["summary"] = (new MasterySummary());
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {MasteryItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteryView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasteryView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField0_0($$parsedSource["summary"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new MasteryView(/** @type {Partial<MasteryView>} */($$parsedSource));
    }
}

/**
 * RelicReward is one possible drop from a relic, valued and flagged with whether
 * the player already owns it.
 */
export class RelicReward {
    /**
     * Creates a new RelicReward instance.
     * @param {Partial<RelicReward>} [$$source = {}] - The source object to create the RelicReward.
     */
    constructor($$source = {}) {
        if (!("part" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["part"] = "";
        }
        if (!("rarity" in $$source)) {
            /**
             * Common | Uncommon | Rare
             * @member
             * @type {string}
             */
            this["rarity"] = "";
        }
        if (!("chance" in $$source)) {
            /**
             * drop chance in percent
             * @member
             * @type {number}
             */
            this["chance"] = 0;
        }
        if (!("plat" in $$source)) {
            /**
             * warframe.market value of the part
             * @member
             * @type {number}
             */
            this["plat"] = 0;
        }
        if (!("ducats" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ducats"] = 0;
        }
        if (!("owned" in $$source)) {
            /**
             * how many of this part the player already has
             * @member
             * @type {number}
             */
            this["owned"] = 0;
        }
        if (!("mastered" in $$source)) {
            /**
             * the part's prime set is mastered
             * @member
             * @type {boolean}
             */
            this["mastered"] = false;
        }
        if (!("crafted" in $$source)) {
            /**
             * a copy of the set is built/owned
             * @member
             * @type {boolean}
             */
            this["crafted"] = false;
        }
        if (!("setName" in $$source)) {
            /**
             * the prime set this part belongs to
             * @member
             * @type {string}
             */
            this["setName"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * thumbnail URL for the part
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelicReward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelicReward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelicReward(/** @type {Partial<RelicReward>} */($$parsedSource));
    }
}

/**
 * RelicRow is one owned relic variant with its drop table.
 */
export class RelicRow {
    /**
     * Creates a new RelicRow instance.
     * @param {Partial<RelicRow>} [$$source = {}] - The source object to create the RelicRow.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * "Lith D1"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("era" in $$source)) {
            /**
             * Lith | Meso | Neo | Axi | Requiem
             * @member
             * @type {string}
             */
            this["era"] = "";
        }
        if (!("refinement" in $$source)) {
            /**
             * Intact | Exceptional | Flawless | Radiant
             * @member
             * @type {string}
             */
            this["refinement"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }
        if (!("value" in $$source)) {
            /**
             * expected platinum per crack (Σ chance×plat)
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("rewards" in $$source)) {
            /**
             * @member
             * @type {RelicReward[]}
             */
            this["rewards"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelicRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelicRow}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rewards" in $$parsedSource) {
            $$parsedSource["rewards"] = $$createField5_0($$parsedSource["rewards"]);
        }
        return new RelicRow(/** @type {Partial<RelicRow>} */($$parsedSource));
    }
}

/**
 * RelicsView is the relics tab payload.
 */
export class RelicsView {
    /**
     * Creates a new RelicsView instance.
     * @param {Partial<RelicsView>} [$$source = {}] - The source object to create the RelicsView.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * total relics held
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("types" in $$source)) {
            /**
             * distinct relic variants held
             * @member
             * @type {number}
             */
            this["types"] = 0;
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {RelicRow[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelicsView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RelicsView}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        return new RelicsView(/** @type {Partial<RelicsView>} */($$parsedSource));
    }
}

export class SellItem {
    /**
     * Creates a new SellItem instance.
     * @param {Partial<SellItem>} [$$source = {}] - The source object to create the SellItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("qty" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["qty"] = 0;
        }
        if (!("plat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["plat"] = 0;
        }
        if (!("live" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["live"] = 0;
        }
        if (!("ducats" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ducats"] = 0;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SellItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SellItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SellItem(/** @type {Partial<SellItem>} */($$parsedSource));
    }
}

export class TradeRow {
    /**
     * Creates a new TradeRow instance.
     * @param {Partial<TradeRow>} [$$source = {}] - The source object to create the TradeRow.
     */
    constructor($$source = {}) {
        if (!("partner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["partner"] = "";
        }
        if (!("gave" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gave"] = "";
        }
        if (!("received" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["received"] = "";
        }
        if (!("platDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platDelta"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TradeRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TradeRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TradeRow(/** @type {Partial<TradeRow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TradeRow.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CraftNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = InvItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = MasteryPart.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = MasterySummary.createFrom;
const $$createType10 = MasteryItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = RelicReward.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = RelicRow.createFrom;
const $$createType15 = $Create.Array($$createType14);
