// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Analytics {
    /**
     * Creates a new Analytics instance.
     * @param {Partial<Analytics>} [$$source = {}] - The source object to create the Analytics.
     */
    constructor($$source = {}) {
        if (!("invValue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["invValue"] = 0;
        }
        if (!("ducats" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ducats"] = 0;
        }
        if (!("sellable" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sellable"] = 0;
        }
        if (!("tradeCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tradeCount"] = 0;
        }
        if (!("netPlat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["netPlat"] = 0;
        }
        if (!("platIn" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platIn"] = 0;
        }
        if (!("platOut" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platOut"] = 0;
        }
        if (!("cumulative" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["cumulative"] = [];
        }
        if (!("recent" in $$source)) {
            /**
             * @member
             * @type {TradeRow[]}
             */
            this["recent"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Analytics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Analytics}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cumulative" in $$parsedSource) {
            $$parsedSource["cumulative"] = $$createField7_0($$parsedSource["cumulative"]);
        }
        if ("recent" in $$parsedSource) {
            $$parsedSource["recent"] = $$createField8_0($$parsedSource["recent"]);
        }
        return new Analytics(/** @type {Partial<Analytics>} */($$parsedSource));
    }
}

/**
 * InvCategory groups inventory items.
 */
export class InvCategory {
    /**
     * Creates a new InvCategory instance.
     * @param {Partial<InvCategory>} [$$source = {}] - The source object to create the InvCategory.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {InvItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvCategory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InvCategory}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new InvCategory(/** @type {Partial<InvCategory>} */($$parsedSource));
    }
}

/**
 * InvItem is a displayed inventory item.
 */
export class InvItem {
    /**
     * Creates a new InvItem instance.
     * @param {Partial<InvItem>} [$$source = {}] - The source object to create the InvItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rank"] = 0;
        }
        if (!("maxRank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRank"] = 0;
        }
        if (!("mastered" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mastered"] = false;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InvItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InvItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InvItem(/** @type {Partial<InvItem>} */($$parsedSource));
    }
}

/**
 * ListResult reports the outcome of posting sell orders.
 */
export class ListResult {
    /**
     * Creates a new ListResult instance.
     * @param {Partial<ListResult>} [$$source = {}] - The source object to create the ListResult.
     */
    constructor($$source = {}) {
        if (!("listed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["listed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListResult(/** @type {Partial<ListResult>} */($$parsedSource));
    }
}

/**
 * LoadStatus reports whether the inventory is loaded and any error.
 */
export class LoadStatus {
    /**
     * Creates a new LoadStatus instance.
     * @param {Partial<LoadStatus>} [$$source = {}] - The source object to create the LoadStatus.
     */
    constructor($$source = {}) {
        if (!("loaded" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loaded"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadStatus(/** @type {Partial<LoadStatus>} */($$parsedSource));
    }
}

/**
 * MarketSeller is one warframe.market seller of a part, with a ready-to-send
 * in-game whisper to buy it.
 */
export class MarketSeller {
    /**
     * Creates a new MarketSeller instance.
     * @param {Partial<MarketSeller>} [$$source = {}] - The source object to create the MarketSeller.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("platinum" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platinum"] = 0;
        }
        if (!("quantity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quantity"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * ingame | online | offline
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("whisper" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["whisper"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketSeller instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketSeller}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarketSeller(/** @type {Partial<MarketSeller>} */($$parsedSource));
    }
}

export class MarketStatus {
    /**
     * Creates a new MarketStatus instance.
     * @param {Partial<MarketStatus>} [$$source = {}] - The source object to create the MarketStatus.
     */
    constructor($$source = {}) {
        if (!("loggedIn" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["loggedIn"] = false;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MarketStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarketStatus(/** @type {Partial<MarketStatus>} */($$parsedSource));
    }
}

export class MasteryItem {
    /**
     * Creates a new MasteryItem instance.
     * @param {Partial<MasteryItem>} [$$source = {}] - The source object to create the MasteryItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * "Mastered" etc (display string)
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("rank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rank"] = 0;
        }
        if (!("maxRank" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxRank"] = 0;
        }
        if (!("partsOwned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["partsOwned"] = 0;
        }
        if (!("partsTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["partsTotal"] = 0;
        }
        if (!("parts" in $$source)) {
            /**
             * per-component detail (collecting items)
             * @member
             * @type {MasteryPart[]}
             */
            this["parts"] = [];
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasteryItem}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parts" in $$parsedSource) {
            $$parsedSource["parts"] = $$createField7_0($$parsedSource["parts"]);
        }
        return new MasteryItem(/** @type {Partial<MasteryItem>} */($$parsedSource));
    }
}

/**
 * MasteryPart is one recipe component with how many the player owns vs needs
 * (recipes can require more than one, e.g. two blades).
 */
export class MasteryPart {
    /**
     * Creates a new MasteryPart instance.
     * @param {Partial<MasteryPart>} [$$source = {}] - The source object to create the MasteryPart.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * "<item> <component>" for market lookup
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("have" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["have"] = 0;
        }
        if (!("need" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["need"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteryPart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasteryPart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasteryPart(/** @type {Partial<MasteryPart>} */($$parsedSource));
    }
}

export class MasterySummary {
    /**
     * Creates a new MasterySummary instance.
     * @param {Partial<MasterySummary>} [$$source = {}] - The source object to create the MasterySummary.
     */
    constructor($$source = {}) {
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }
        if (!("Mastered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Mastered"] = 0;
        }
        if (!("BuiltUnranked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["BuiltUnranked"] = 0;
        }
        if (!("ReadyToBuild" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ReadyToBuild"] = 0;
        }
        if (!("PartsPartial" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PartsPartial"] = 0;
        }
        if (!("NotStarted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["NotStarted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterySummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterySummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterySummary(/** @type {Partial<MasterySummary>} */($$parsedSource));
    }
}

export class MasteryView {
    /**
     * Creates a new MasteryView instance.
     * @param {Partial<MasteryView>} [$$source = {}] - The source object to create the MasteryView.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {MasterySummary}
             */
            this["summary"] = (new MasterySummary());
        }
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {MasteryItem[]}
             */
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteryView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasteryView}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField0_0($$parsedSource["summary"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new MasteryView(/** @type {Partial<MasteryView>} */($$parsedSource));
    }
}

export class SellItem {
    /**
     * Creates a new SellItem instance.
     * @param {Partial<SellItem>} [$$source = {}] - The source object to create the SellItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("qty" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["qty"] = 0;
        }
        if (!("plat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["plat"] = 0;
        }
        if (!("live" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["live"] = 0;
        }
        if (!("ducats" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ducats"] = 0;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SellItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SellItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SellItem(/** @type {Partial<SellItem>} */($$parsedSource));
    }
}

export class TradeRow {
    /**
     * Creates a new TradeRow instance.
     * @param {Partial<TradeRow>} [$$source = {}] - The source object to create the TradeRow.
     */
    constructor($$source = {}) {
        if (!("partner" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["partner"] = "";
        }
        if (!("gave" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gave"] = "";
        }
        if (!("received" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["received"] = "";
        }
        if (!("platDelta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["platDelta"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TradeRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TradeRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TradeRow(/** @type {Partial<TradeRow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TradeRow.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = InvItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = MasteryPart.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = MasterySummary.createFrom;
const $$createType8 = MasteryItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
