// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound API: its exported methods are callable from the
 * frontend. It wraps the pure-Go domain packages (shared with the overlay).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAnalytics returns inventory value plus tracked-trade stats.
 * @returns {$CancellablePromise<$models.Analytics>}
 */
export function GetAnalytics() {
    return $Call.ByID(2768680213).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetInventory returns owned equipment grouped by category with names, ranks and
 * thumbnails.
 * @returns {$CancellablePromise<$models.InvCategory[]>}
 */
export function GetInventory() {
    return $Call.ByID(1453675977).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetMastery computes the best-to-do-next mastery view.
 * @returns {$CancellablePromise<$models.MasteryView>}
 */
export function GetMastery() {
    return $Call.ByID(4196764460).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSellable lists owned tradeable parts with prices and thumbnails.
 * @returns {$CancellablePromise<$models.SellItem[]>}
 */
export function GetSellable() {
    return $Call.ByID(340323687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListOnMarket posts visible sell orders for the named items at their price.
 * @param {string[]} names
 * @returns {$CancellablePromise<$models.ListResult>}
 */
export function ListOnMarket(names) {
    return $Call.ByID(3721823692, names).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * LoadInventory loads the player inventory (from $WFO_INVENTORY_FILE if set, else
 * by scraping the running game).
 * @returns {$CancellablePromise<$models.LoadStatus>}
 */
export function LoadInventory() {
    return $Call.ByID(1450154683).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * MarketLogin signs in and (on success) saves the credentials.
 * @param {string} email
 * @param {string} password
 * @returns {$CancellablePromise<$models.MarketStatus>}
 */
export function MarketLogin(email, password) {
    return $Call.ByID(996785430, email, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MarketLogout() {
    return $Call.ByID(506415703);
}

/**
 * @returns {$CancellablePromise<$models.MarketStatus>}
 */
export function MarketStatus() {
    return $Call.ByID(1682935395).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * RefreshLivePrices fetches warframe.market median prices for the given items.
 * @param {string[]} names
 * @returns {$CancellablePromise<void>}
 */
export function RefreshLivePrices(names) {
    return $Call.ByID(2736758036, names);
}

// Private type creation functions
const $$createType0 = $models.Analytics.createFrom;
const $$createType1 = $models.InvCategory.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.MasteryView.createFrom;
const $$createType4 = $models.SellItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ListResult.createFrom;
const $$createType7 = $models.LoadStatus.createFrom;
const $$createType8 = $models.MarketStatus.createFrom;
