// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound API: its exported methods are callable from the
 * frontend. It wraps the pure-Go domain packages (shared with the overlay).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAnalytics returns inventory value plus tracked-trade stats.
 * @returns {$CancellablePromise<$models.Analytics>}
 */
export function GetAnalytics() {
    return $Call.ByID(2768680213).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCraftingTree returns the recipe tree for the named item: each component
 * with how many the recipe needs and how many the player owns, recursing into
 * buildable components (e.g. Excalibur → Chassis blueprint → Ferrite/Rubedo).
 * Resource drop-locations and build times are intentionally not included.
 * @param {string} itemName
 * @returns {$CancellablePromise<$models.CraftNode>}
 */
export function GetCraftingTree(itemName) {
    return $Call.ByID(1111094725, itemName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetInventory returns owned equipment grouped by category with names, ranks and
 * thumbnails.
 * @returns {$CancellablePromise<$models.InvCategory[]>}
 */
export function GetInventory() {
    return $Call.ByID(1453675977).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetMastery computes the mastery view, ordered by sortMode: "next" (best to do
 * next, the default), "cost" (cheapest missing parts to buy first) or "relics"
 * (most farmable from relics the player already owns first).
 * @param {string} sortMode
 * @returns {$CancellablePromise<$models.MasteryView>}
 */
export function GetMastery(sortMode) {
    return $Call.ByID(4196764460, sortMode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetRelics lists the relics the player owns with each relic's drop table, the
 * platinum/ducat value and ownership of every reward, and the expected platinum
 * per crack. sortMode is "era" (default), "value" or "count".
 * @param {string} sortMode
 * @returns {$CancellablePromise<$models.RelicsView>}
 */
export function GetRelics(sortMode) {
    return $Call.ByID(2917727547, sortMode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSellable lists owned tradeable parts with prices and thumbnails.
 * @returns {$CancellablePromise<$models.SellItem[]>}
 */
export function GetSellable() {
    return $Call.ByID(340323687).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * InventoryStatus reports the currently held inventory without scraping the
 * game. The frontend calls it after an "inventory:loaded" event to pick up an
 * auto-load done by the background watcher.
 * @returns {$CancellablePromise<$models.LoadStatus>}
 */
export function InventoryStatus() {
    return $Call.ByID(487357017).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListOnMarket posts visible sell orders for the named items at their price.
 * @param {string[]} names
 * @returns {$CancellablePromise<$models.ListResult>}
 */
export function ListOnMarket(names) {
    return $Call.ByID(3721823692, names).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * LoadInventory loads the player inventory (from $WFO_INVENTORY_FILE if set, else
 * by scraping the running game).
 * @returns {$CancellablePromise<$models.LoadStatus>}
 */
export function LoadInventory() {
    return $Call.ByID(1450154683).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * MarketLogin signs in and (on success) saves the credentials.
 * @param {string} email
 * @param {string} password
 * @returns {$CancellablePromise<$models.MarketStatus>}
 */
export function MarketLogin(email, password) {
    return $Call.ByID(996785430, email, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function MarketLogout() {
    return $Call.ByID(506415703);
}

/**
 * @returns {$CancellablePromise<$models.MarketStatus>}
 */
export function MarketStatus() {
    return $Call.ByID(1682935395).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * PartSellers looks up warframe.market sellers for a part (by its "<item>
 * <component>" query) and returns each with a copyable purchase whisper.
 * @param {string} query
 * @returns {$CancellablePromise<$models.MarketSeller[]>}
 */
export function PartSellers(query) {
    return $Call.ByID(1999966532, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * RefreshLivePrices fetches warframe.market median prices for the given items.
 * @param {string[]} names
 * @returns {$CancellablePromise<void>}
 */
export function RefreshLivePrices(names) {
    return $Call.ByID(2736758036, names);
}

// Private type creation functions
const $$createType0 = $models.Analytics.createFrom;
const $$createType1 = $models.CraftNode.createFrom;
const $$createType2 = $models.InvCategory.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.MasteryView.createFrom;
const $$createType5 = $models.RelicsView.createFrom;
const $$createType6 = $models.SellItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.LoadStatus.createFrom;
const $$createType9 = $models.ListResult.createFrom;
const $$createType10 = $models.MarketStatus.createFrom;
const $$createType11 = $models.MarketSeller.createFrom;
const $$createType12 = $Create.Array($$createType11);
